/*
 * @Author: WinstonRD
 * @Date: 2025-07-15 19:44:12
 * @LastEditors: WinstonRD && winstonz919@sina.com
 * @LastEditTime: 2025-07-15 19:48:19
 * @FilePath: /33-go-zero/grpc-server/internal/server/greetserver.go
 * @Description:
 *
 * Copyright (c) 2025 by WinstonRD, All Rights Reserved.
 */
// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: greet.proto

package server

import (
	"context"

	"grpc-server/greet"
	"grpc-server/internal/logic"
	"grpc-server/internal/svc"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	greet.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

func (s *GreetServer) Ping(ctx context.Context, in *greet.Request) (*greet.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
